System Reliability Analysis
pystra/pystra pull request #23
Opened 2021-11-19 07:32 UTC by mayermelhem

Hello `pystra` team! 

`pystra` is mostly framed as a component reliability analysis toolbox. My research tends to focus on system reliability/risk. So rather than reinvent the wheel, I have ported over today some of my personal code into `pystra` to kick-start the develop of a system reliability analysis toolbox. 

The code, based on the [Matrix-Based System Reliability (MSR) Method](https://www.sciencedirect.com/science/article/pii/S0951832008000392), is currently in a single `system.py` script inside a separate `system` folder.  I figured perhaps more scripts would be necessary as the toolbox grows.  Series only, Parallel only, and Series-Parallel systems can be created. To consider correlations, the mutually-exclusive collective-exhaustive (MECE) event probabilities are currently calculated using the [Equivalent Planes Method (EPM)](https://www.sciencedirect.com/science/article/pii/S0167473015000600?via%3Dihub). Ideally, other methods should be adopted, including Monte Carlo simulation. 

An example of usage for system reliability is seen in the `examples` folder (see `system_reliability.py`).  

I am still to validate correlation in the example, and explore a large scale system. Therefore, look-out perhaps for further commits in this PR. 

Hope you enjoy it, appreciate comments and feedback!

2021-11-20 03:57 UTC, ccaprani requested changes
This is a wonderful contribution! Thank you so much!

I think the `system` module can be in the main pystra folder - it's not an overly long module and doesn't require multiple files, so pystra/system.py is fine.

There are other comments for the code too. 

Can you consider adding to the documentation about this functionality as well please?

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +
Is there a published benchmark problem to test the code on? Prefereably from a textbook or similar

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +# from scipy.stats import norm, lognorm, uniform
Please format with black and check the warnings.

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +
Is there a meaning behind the variables? Or is it just a numerical excercise?

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +comp1.addVariable(rv_1)
If the variables have a physical interpretation be good to use this for variable names.

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +
The interface is really nice!

2021-11-20 03:57 UTC, ccaprani commented on examples/system_reliability.py
> +serpar_reliability = serpar_sys.getReliability()
Comparison to established results would be ideal.

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +    A component within a system described by a limit state
Can a component have just one LSF? Or could the LSF be changed? I think what you have is right in the sense that the RVs in a component will be described with respect to a single LSF usually; but perhaps sometimes not?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +    def addVariable(self,obj):
`snake_case` for function names please!

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        # For now, using default options
Be good if user can assign preferred options; especially in relation to terminal output which may not be desired.

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        beta = float(analysis.beta)
Can remove comments that don't really add value - the code here (and similar such cases) is clear.

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +    (either in series/paralel/both)
Make clear the algorithim used - equivalent planes here? And what alternatives might be added in the future?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        # TODO: stochasticmodel?
Regarding `TODO`s - is it not yet complete? If it is, please remove these.

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +                self.components = self.components + obj.components
`self.components += obj.components`

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        using alpha_hat (Roscoe, 2015)."""
Please give reference explicitly in class docstring. Also, if there is another algorithim (even if not yet implemented), how can user select?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        # event vector obtained through init
Raise warning if `method is not "epm"`

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +            # TODO: Check alpha hat dimensions are correct
Maybe check when adding at Line 140?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +            # Step 1: Get component probabilities
If new methods will be added, each could have their own function so that this functions is not too long?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        # calculate series system event vector
Looks like a comment for the function or class docstring?

2021-11-20 03:57 UTC, ccaprani commented on pystra/system/system.py
> +        # calculate series system event vector
Ditto

2021-11-22 03:03 UTC, mayermelhem commented on pystra/system/system.py
> +            # Step 1: Get component probabilities
A valid point. Would the script then also be too long, requiring the folder rather than a single script?

2021-11-22 03:03 UTC, mayermelhem commented on pystra/system/system.py
> +                self.components = self.components + obj.components
Indeed!

2021-11-22 03:04 UTC, mayermelhem commented on pystra/system/system.py
> +    (either in series/paralel/both)
The only other alternative I can think of is MCS.

2021-11-22 03:05 UTC, mayermelhem commented on pystra/system/system.py
> +    def addVariable(self,obj):
Currently not `snake_case` in `pystra`

2021-11-22 03:07 UTC, mayermelhem commented on pystra/system/system.py
> +    A component within a system described by a limit state
`Component` essentially bundles what is currently done by `pystra` for FORM analysis. Hence, there is one limit state function. I will add a `setLimitState()` method if you wish to change the limit state.

2021-11-22 03:07 UTC, mayermelhem commented on examples/system_reliability.py
> +
Thank you!

2021-11-22 03:16 UTC, mayermelhem commented on pystra/system/system.py
> +        # For now, using default options
`analysis_options` included as kwargs for component

2021-11-22 03:20 UTC, mayermelhem commented on pystra/system/system.py
> +        # calculate series system event vector
Changes made

2021-11-22 03:20 UTC, mayermelhem commented on pystra/system/system.py
> +        # calculate series system event vector
Ditto

2021-11-22 03:33 UTC, mayermelhem commented on pystra/system/system.py
> +            # TODO: Check alpha hat dimensions are correct
Good idea. Done.

2021-11-22 03:34 UTC, mayermelhem commented on pystra/system/system.py
> +        # event vector obtained through init
Warning raised in `getEventProbabilities`

2021-11-22 03:37 UTC, mayermelhem commented on pystra/system/system.py
> +        using alpha_hat (Roscoe, 2015)."""
Reference here was for personal reasons, will move to the documentation,

2021-11-24 02:52 UTC, mayermelhem commented on examples/system_reliability.py
> +
This was based on my thesis. I have updated the file to include three examples from literature. Consequently, it appears the work is incomplete for autocorrelation between limit state different to 0 and 1.

2021-11-24 02:53 UTC, mayermelhem commented on examples/system_reliability.py
> +
It is an example. Nevertheless, this has been removed now.

2021-11-24 02:53 UTC, mayermelhem commented on examples/system_reliability.py
> +comp1.addVariable(rv_1)
This has been removed now.

2021-11-24 02:53 UTC, mayermelhem commented on examples/system_reliability.py
> +serpar_reliability = serpar_sys.getReliability()
Please see the new examples.

2021-11-24 02:54 UTC, mayermelhem commented on pystra/system/system.py
> +        # TODO: stochasticmodel?
All `TODO`s have been removed. However, there is still work to be done (eg. autocorrelation not between 0 and 1).

2021-11-24 02:55 UTC, mayermelhem commented on pystra/system/system.py
> +        beta = float(analysis.beta)
Done.

2021-11-24 03:08 UTC, mayermelhem commented
In the latest commit: 

1. Some changes to the `system.py` to address correlation between random variables in the same component, and correlations between the same random variables in different components (ie. autocorrelation), which then give rise to the correlation between components.
2.  Three examples from the literature in `system_reliability.py` to demonstrate and validate. However, validation appears only suitable for autocorrelations of 0 or 1. 

I will focus on the documentation and make sure formatting is done to black.

2021-11-24 05:28 UTC, ccaprani requested changes
Thanks. This is really super! The documentation and the limitations to the correlation cases is critical to even just warn users about before we can merge I think.

2021-11-24 05:28 UTC, ccaprani commented on examples/system_reliability.py
> +# parallel system does not. (ductile system?)
It's important we know why this does not match. Although there is a liability waiver, users will expect the code to be correct. Is it a problem with the code, or the example in the book? Is there another similar example that shows the code is correct but the book is wrong? Perhaps it just needs the FORM analysis options to be tuned a little?

2021-11-24 05:28 UTC, ccaprani commented on examples/system_reliability.py
> +print(series_sys.getReliability())
Is there a comparison value from the source?

2021-11-24 05:28 UTC, ccaprani commented on examples/system_reliability.py
> +
> Consequently, it appears the work is incomplete for autocorrelation between limit state different to 0 and 1.

I'm not quite sure what this means - which work? This code, or your thesis? If this code, what is needed to complete it? What limitations should the user be aware of? Is a warning notice needed to guide the user on the limit of applicability?

2021-11-24 05:28 UTC, ccaprani commented on examples/system_reliability.py
> +
Super!

2021-11-24 05:28 UTC, ccaprani commented on pystra/system/system.py
>              print("Only equivalent planes method currently supported")
`raise ValueError`? Analysis should not proceed if not `epm`, correct?

2021-11-24 08:06 UTC, mayermelhem commented on examples/system_reliability.py
> +# parallel system does not. (ductile system?)
I agree. This needs more thinking to understand why.

2021-11-24 08:08 UTC, mayermelhem commented on examples/system_reliability.py
> +print(series_sys.getReliability())
This one wasn't matching, but then again, I don't know if it is an isolated case (paper wrong or code wrong).

2021-11-24 08:13 UTC, mayermelhem commented on pystra/system/system.py
>              print("Only equivalent planes method currently supported")
Added.

2021-11-24 08:18 UTC, mayermelhem commented
Documentation now added. 

I don't know why the black checks are failing ... I thought I have installed the formatted correctly. 

Upon reviewing my notes, I've realised that the algorithm currently used is not strictly epm per se, but also a modification of sequential compound method.
A second eyes on the algorithm is worth teasing out before merging to make sure it is valid. We see that it works for some examples and not some others. Perhaps more examples are needed too?

2021-11-25 06:40 UTC, Jungle-13 commented
thank you ,sir! I Iinstalled this python package with the pycharm compiler, but I couldn't import it! So would you loke to tell the reason of this!Many thanks!

2021-12-02 01:33 UTC, mayermelhem commented
Simple bounds (for all series or all parallel) and Ditlevsen bounds (for all series) now included. Examples also updated to validate they are correct. The pipeline example is not matching per publication and needs further teasing.  However, Ditlevsen bounds match the system reliability estimate. 

Upon coding I have come to realise that the system reliability is really calculated using first-order system probability (see pg 281 in Lemaire), with `scipy.stats.multivariate_normal` used. The same is adopted for find joint probabilities (bivariate) necessary with Ditlevsen bounds. Note that instead the probabilities of MECE are calculated, as inspired by the matrix-based system reliability method, allowing mixed systems to be explored. This has been updated in the documentation. Indeed, as the number of components increase in the system, evaluating the multi-variate normal is cumbersome as thus alternative methods may need to be explored. Some alternative methods are indicated in the documentation.

2021-12-02 02:47 UTC, ccaprani reviewed
We shouldn't merge until the problem is resolved either way, but super developments - thank you!

2021-12-02 02:47 UTC, ccaprani commented on pystra/system/system.py
> +    def bounds_default(self):
Suggestion that there is just a public `bounds` function with a kwarg to select the bounds type, e.g. `sys.bounds(bounds_type='basic')` (presuming that Ditlevsen would be default. This public API wrapper could just call the internal functions `_bounds_basic` and `_bounds_ditlevsen` as appropriate. (I am suggesting `basic` rather than `default` as a name too).

2021-12-02 02:47 UTC, ccaprani commented on examples/system_reliability.py
> +# 63.8e-4 to 64.2e-4
Seems like we should use these examples in a test suite...even though they'd currently fail.

2021-12-07 04:50 UTC, mayermelhem commented on pystra/system/system.py
> +    def bounds_default(self):
There is a `getBounds()` function in the `System` Class. I have changed to `basic` rather than `default`.

2021-12-07 05:42 UTC, ccaprani reviewed
Great changes - thanks. There are a few black errors to be fixed. Also, any match with an benchmark result yet?

2021-12-07 05:42 UTC, ccaprani commented on pystra/system/__init__.py
> +from .system import *  # currently a single script, need more?
single script is fine.

2021-12-07 05:42 UTC, ccaprani commented on pystra/__init__.py
> +
Can you fix the black errors please?

2021-12-18 14:23 UTC, Jungle-13 commented
Hello, sir.
I take the liberty to disturb you!
I am having trouble using pystra.
I feel confident that there is nothing wrong with this program, but it is an error.
The error is ``TypeError:'numpy.ndarray' object is not callable''
Teacher, is it convenient for you to take a look for me?
The attachment is a specific file, thank you!
Best wishes!
Wang Zhangong
School of Civil Engineering, Harbin Institute of Technology, China





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pystra/pystra"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pystra/pystra] System Reliability Analysis (PR #23)





 
@ccaprani commented on this pull request.
 
Great changes - thanks. There are a few black errors to be fixed. Also, any match with an benchmark result yet?

 
In pystra/system/__init__.py:
 &gt; @@ -0,0 +1,2 @@ +# System reliability analysis +from .system import *  # currently a single script, need more?  
single script is fine.
 
 
In pystra/__init__.py:
 &gt; @@ -41,3 +41,6 @@  from .mc import *  from .sorm import *  from .sensitivity import * +  
Can you fix the black errors please?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2022-05-01 10:49 UTC, ccaprani commented
@mayermelhem are you able to finalize this PR?

2022-05-07 07:35 UTC, closed without merging